os: linux
dist: trusty
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam
  - $HOME/bin

addons:
  apt:
    sources:
    - avsm

env:
  global:
  - NJOBS=2
  - COMPILER="4.07.1"
  - FINDLIB_VER="1.8.0"
  - EQUATIONS_VER="dev"
  - COQ_VER="dev"

install:
- curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh > install.sh
- export PATH=$HOME/bin:$PATH
- which opam || (rm -rf $HOME/.opam; echo $HOME/bin | sudo sh install.sh --no-backup; opam init --disable-sandboxing -j ${NJOBS} --compiler=${COMPILER} -n -y)
- opam --version
- opam update -y
- opam init -j ${NJOBS} -n -y --compiler=$COMPILER
- opam switch create ${COMPILER} || echo "switch already exists"
- opam switch set ${COMPILER}
- eval $(opam config env)
- opam config list
- opam repo add coq-released https://coq.inria.fr/opam/released || echo "coq-released registered"
- opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev || echo "coq-core-dev registered"
- opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev || echo "coq-extra-dev registered"
- opam install -j ${NJOBS} -y ocamlfind.${FINDLIB_VER} coq.${COQ_VER} coq-equations.${EQUATIONS_VER}
- opam list

jobs:
  include:
    - name: "Local build"
      env: TARGET=local
    - name: "Opam installation"
      env: TARGET=opam

script:
 - ./configure.sh ${TARGET}
 - make -j ${NJOBS} ci-${TARGET}

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1d832177d55504ef1fba
      - https://webhooks.gitter.im/e/16c924039f492c4a5640
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
