name: MetaCoq CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        coq_version:
          - '8.13'
        ocaml_version:
          - '4.07-flambda'
          - '4.10-flambda'
          - '4.11-flambda'
        target: [ opam ]
      fail-fast: true

    steps:

      - name: Docker-Coq-Action
        uses: coq-community/docker-coq-action@v1
        with:
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          before_script: |
            startGroup "Workaround permission issue"
              sudo chown -R coq:coq .  # <--
              opam exec -- ocamlfind list
            endGroup
          script: |
            startGroup "Build project"
              opam exec -- ./configure.sh --enable-${{matrix.target}}
              opam exec -- make -j 2 ci-${{matrix.target}}
            endGroup
          uninstall: |
            startGroup "Clean project"
            endGroup

      - name: Revert permissions
        # to avoid a warning at cleanup time
        if: ${{ always() }}
        run: sudo chown -R 1001:116 .  # <--
        
      - name: Installing dependencies
        run: opam install . --deps-only --with-doc --with-test

      - name: Configuring
        run: opam exec -- ./configure.sh ${{matrix.target}}
      - name: Compiling
        run: opam exec -- make -j 2 ci-${{matrix.target}}
