name: Test compilation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ local, opam ]

    steps:

      - name: Get current Coq head commit
        id: get-commit
        run: |
          echo "::set-output name=hash::$(git ls-remote https://github.com/coq/coq refs/heads/master | cut -f 1)"
        shell: bash

      - name: Try to restore opam cache
        id: opam-cache
        uses: actions/cache@v2
        with:
          path: "~/.opam"
          key: opam-${{github.base_ref}}-${{github.ref}}-${{steps.get-commit.outputs.hash}}
          restore-keys: |
            opam--refs/heads/${{github.base_ref}}-${{steps.get-commit.outputs.hash}}

      - name: Install OCaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.07.1

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - run: opam repo add coq-released https://coq.inria.fr/opam/released
      - run: opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev
      - run: opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev
      - run: opam install . --deps-only --with-doc --with-test

      - run: opam exec -- ./configure.sh ${{matrix.target}}
      - run: opam exec -- make -j 2 ci-${{matrix.target}}
